---
# =================================================================================================
# Site Configurations
# =================================================================================================
site_name: LFCS Study Guide
# site_url: https://docs.mirceanton.com/amir-hlb
site_author: Mircea-Pavel Anton
# site_description:
# copyright:
extra:
  version: 1.0.0

# =================================================================================================
# Repo Setup
# =================================================================================================
repo_name: mirceanton/LFCS-Study-Guide
repo_url: https://github.com/mirceanton/LFCS-Study-Guide

# =================================================================================================
# Theme Configuration
# =================================================================================================
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Cascadia Code PL
    code: Cascadia Mono PL
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - search.share
    - search.suggest
    - toc.follow