---
# =================================================================================================
# Site Configurations
# =================================================================================================
site_name: LFCS Study Guide
# site_url: https://docs.mirceanton.com/amir-hlb
site_author: Mircea-Pavel Anton
# site_description:
# copyright:
extra:
  version: 1.0.0

# =================================================================================================
# Repo Setup
# =================================================================================================
repo_name: mirceanton/LFCS-Study-Guide
repo_url: https://github.com/mirceanton/LFCS-Study-Guide

# =================================================================================================
# Theme Configuration
# =================================================================================================
theme:
  name: material
  logo: images/logo.svg
  favicon: images/logo.svg
  palette:
    - scheme: default
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: Cascadia Code PL
    code: Cascadia Mono PL
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.indexes
    - navigation.tabs
    - search.share
    - search.suggest
    - toc.follow

markdown_extensions:
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true

# =================================================================================================
# Navigation Layout
# =================================================================================================
nav:
  - index.md

  - Topics:
    - Essential Commands:
      - Index: Topics/Essential_Commands/index.md
      - Log into local & remote graphical and text mode consoles: Topics/Essential_Commands/Log into local & remote graphical and text mode consoles.md
      - Read, and use system documentation: Topics/Essential_Commands/Read, and use system documentation.md
      - Create, delete, copy, and move files and directories: Topics/Essential_Commands/Create, delete, copy, and move files and directories.md
      - Create and manage hard and soft links: Topics/Essential_Commands/Create and manage hard and soft links.md
      - List, set, and change standard file permissions: Topics/Essential_Commands/List, set, and change standard file permissions.md
      - Advanced File Permissions:
        - SUID: Topics/Essential_Commands/SUID.md
        - SGID: Topics/Essential_Commands/SGID.md
        - Sticky Bit: Topics/Essential_Commands/Sticky Bit.md
      - Search for Files: Topics/Essential_Commands/Search for Files.md
      - Compare and manipulate file content: Topics/Essential_Commands/Compare and manipulate file content.md
      - Search for Files: Topics/Essential_Commands/Search for Files.md
      - Analyze text using basic regular expressions: Topics/Essential_Commands/Analyze text using basic regular expressions.md
      - Archive, backup, compress, unpack, and uncompress files: Topics/Essential_Commands/Archive, backup, compress, unpack, and uncompress files.md
      - Input-Output redirection: Topics/Essential_Commands/Input-Output redirection.md

    - Operation of Running Systems:
      - Index: Topics/Operation_of_Running_Systems/index.md
      - Boot, Reboot and Shutdown: Topics/Operation_of_Running_Systems/Boot, Reboot and Shutdown.md
      - Managing Available Resources: Topics/Operation_of_Running_Systems/Managing Available Resources.md
      - Managing Bootloaders: Topics/Operation_of_Running_Systems/Managing Bootloaders.md
      - Managing Kernel Parameters: Topics/Operation_of_Running_Systems/Managing Kernel Parameters.md
      - Managing Log Files: Topics/Operation_of_Running_Systems/Managing Log Files.md
      - Managing Processes: Topics/Operation_of_Running_Systems/Managing Processes.md
      - Managing SELinux: Topics/Operation_of_Running_Systems/Managing SELinux.md
      - Managing Services: Topics/Operation_of_Running_Systems/Managing Services.md
      - Managing Software Packages: Topics/Operation_of_Running_Systems/Managing Software Packages.md
      - Operating Modes: Topics/Operation_of_Running_Systems/Operating Modes.md
      - Scheduling Tasks: Topics/Operation_of_Running_Systems/Scheduling Tasks.md


    - User and Group Management:
      - Index: Topics/User_and_Group_Management/index.md
      - Managing Local Users: Topics/User_and_Group_Management/Managing Local Users.md
      - Managing Local Groups: Topics/User_and_Group_Management/Managing Local Groups.md
      - Managing User Privileges: Topics/User_and_Group_Management/Managing User Privileges.md
      - Managing User Resource Limits: Topics/User_and_Group_Management/User Resource Limits.md
      - System-wide Environment Profiles: Topics/User_and_Group_Management/System-wide Environment Profiles.md
      - Configure PAM: Topics/User_and_Group_Management/Configure PAM.md

    - Networking:
      - Index: Topics/Networking/index.md
      - Basic Networking Commands: Topics/Networking/Basic Networking Commands.md
      - Managing Hostname: Topics/Networking/Managing Hostname.md
      - Managing Network Services: Topics/Networking/Managing Network Services.md
      - Managing NTP: Topics/Networking/Managing NTP.md
      - Managing Routes: Topics/Networking/Managing Routes.md
      - Managing the Firewall: Topics/Networking/Managing the Firewall.md

    - Service Configuration:
      - Index: Topics/Service_Configuration/index.md

    - Storage Management:
      - Index: Topics/Storage_Management/index.md
      - Managing Storage Partitions: Topics/Storage_Management/Managing Storage Partitions.md
      - Managing Swap Space: Topics/Storage_Management/Managing Swap Space.md
      - Managing File Systems: Topics/Storage_Management/Managing File Systems.md
      - Managing LVM: Topics/Storage_Management/Managing LVM.md
      - Advanced File System Permissions: Topics/Storage_Management/Advanced File System Permissions.md
      - Managing RAID: Topics/Storage_Management/Managing RAID.md
      - Managing Encrypted Storage: Topics/Storage_Management/Managing Encrypted Storage.md
      - Managing Quotas: Topics/Storage_Management/Managing Quotas.md
